apiVersion: batch/v1
kind: Job
metadata:
  name: jmeterjob
  labels:
    env: test
spec:
  template:
    spec:
      containers:
      - name: jmeter
        image: peltops/gws_jmeter:v1
      restartPolicy: Never